import webbuds1 from './webbuds1.jpg'
import webbuds2 from './webbuds2.jpg'
import webbuds3 from './webbuds3.jpg'
import webbuds4 from './webbuds4.jpg'
import webbuds5 from './webbuds5.jpg'
import webbuds6 from './webbuds6.jpg'
import webbuds7 from './webbuds7.jpg'
import webbuds8 from './webbuds8.jpg'
import webbuds9 from './webbuds9.jpg'



const productListWEB = [
    {
        productid: 'wirelessearbuds1',
        itemName: 'Airdopes 131',
        category: 'wireless earbuds',
        rating: '4.8',
        sold: '1336',
        price: 899,
        priceBefore: '2990',
        discount: '70% off',
        offer: 'Engraving Available',
        usp: '60 Hours Playback',
        usp2 :'13mm Drivers',
        usp3:'IWP Technology',
        image: webbuds1,
        count : 0 ,
        grandtotal :0,
        
    },
    {
        productid: 'wirelessearbuds2',
        itemName: 'Airdopes 181',
        category: 'wireless earbuds',
        rating: '4.9',
        sold: '37',
        price: 1099,
        priceBefore: '2,990',
        discount: '63%',
        offer: 'none',
        usp: '20 Hours Playback',
        usp2 :'Clear Calling',
        usp3:'BEAST Mode',
        image: webbuds2,
        count : 0 ,
        grandtotal :0,
        
    },
    {
        productid: 'wirelessearbuds3',
        itemName: 'Airdopes 115',
        category: 'wireless earbuds',
        rating: '4.9',
        sold: '104',
        price: 1299,
        priceBefore: '2,990',
        discount: '57% off',
        offer: 'none',
        usp: 'Clear Calling',
        usp2 :'13mm Drivers',
        usp3:'BEAST Mode',
        image: webbuds3,
        count : 0 ,
        grandtotal :0,
    },
    {
        productid: 'wirelessearbuds4',
        itemName: 'Airdopes 131 Pro',
        category: 'wireless earbuds',
        rating: '4.9',
        sold: '182',
        price: '999',
        priceBefore: '2,990',
        discount: '67% off',
        offer: 'Engraving Available',
        usp: '45 Hours Playback',
        usp2 :'Clear Calling',
        usp3:'Beast Mode',
        image: webbuds4,
        count : 0 ,
    },
    {
        productid: 'wirelessearbuds5',
        itemName: 'Airdopes Alpha',
        category: 'wireless earbuds',
        rating: '4.9',
        sold: '118',
        price: 899,
        priceBefore: '3,490',
        discount: '74% off',
        offer: 'none',
        usp: '35 Hours Playback',
        usp2 :'ENx Technology',
        usp3:'ASAP charge',
        image: webbuds5,
        count : 0 ,
        grandtotal :0,
    },
    {
        productid: 'wirelessearbuds6',
        itemName: 'Nirvana Ion',
        category: 'wireless earbuds',
        rating: '4.9',
        sold: '54',
        price: 2299,
        priceBefore: '7,990',
        discount: '71% off',
        offer: 'Engraving Available',
        usp: '120 Hours Playback',
        usp2 :'ENx Technology',
        usp3:'Dual EQ Modes',
        image: webbuds6,
        count : 0 ,
    },
    {
        productid: 'wirelessearbuds7',
        itemName: 'Nirvana Ion ANC',
        category: 'wireless earbuds',
        rating: '4.9',
        sold: '81',
        price: 2799,
        priceBefore: '9,990',
        discount: '72% off',
        offer: 'Engraving Available',
        usp: 'Noise Cancellation',
        usp2 :'120 Hours Playback',
        usp3:'BEAST Mode',
        image: webbuds7,
        count : 0 ,
    },
    {
        productid: 'wirelessearbuds8',
        itemName: 'Immortal 171',
        category: 'wireless earbuds',
        rating: '4.7',
        sold: '18',
        price: 1699,
        priceBefore: '3,490',
        discount: '51% off',
        offer: 'none',
        usp: 'Gaming Earbuds',
        usp2 :'Upto 40HRS Playback',
        usp3:'Beast Mode',
        image: webbuds8,
        count : 0 ,
    },
    {
        productid: 'wirelessearbuds9',
        itemName: 'Airdopes 148',
        category: 'wireless earbuds',
        rating: '5.0',
        sold: '148',
        price: 1499,
        priceBefore: '4,490',
        discount: '67% off',
        offer: 'New Launch',
        usp: '42 Hours Playback',
        usp2 :'Clear Calling',
        usp3:'AASAP Charge',
        image: webbuds9,
        count : 0 ,
    },
]
export default productListWEB