import smartwatch1 from './smartwatch1.jpg'
import smartwatch2 from './smartwatch2.jpg'
import smartwatch3 from './smartwatch3.jpg'
import smartwatch4 from './smartwatch4.jpg'
import smartwatch5 from './smartwatch5.jpg'
import smartwatch6 from './smartwatch6.jpg'
import smartwatch7 from './smartwatch7.jpg'
import smartwatch8 from './smartwatch8.jpg'
import smartwatch9 from './smartwatch9.jpg'
import smartwatch10 from './smartwatch10.jpg'
import smartwatch11 from './smartwatch11.jpg'
import smartwatch12 from './smartwatch12.jpg'

const smartWatchesList = [
    
        {
            productid: 'smartwatches1',
            itemName: 'Storm Call',
            category: 'smart watches',
            rating: '4.8',
            sold: '27',
            price: 1499,
            count:0,
            priceBefore: '7,990',
            discount: '81% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'2.5D Curved Display',
            usp3:'Save Upto 10 Contacts',
            image: smartwatch1,
        },
        {
            productid: 'smartwatches2',
            itemName: 'Wave Flex Connect',
            category: 'smart watches',
            rating: '4.8',
            sold: '31',
            price: 1499,
            count:0,
            priceBefore: '7,990',
            discount: '81% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'HD Curved Display',
            usp3:'10 Days Battery Life',
            image: smartwatch2,
        },
        {
            productid: 'smartwatches3',
            itemName: 'Lunar Connect',
            category: 'smart watches',
            rating: '4.9',
            sold: '15',
            price: 1799,
            count:0,
            priceBefore: '7,990',
            discount: '78% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'100+ Sports Modes',
            usp3:'ENx Technology',
            image: smartwatch3,
        },
        {
            productid: 'smartwatches4',
            itemName: 'Wave Beat Call',
            category: 'smart watches',
            rating: '4.8',
            sold: '17',
            price: 1499,
            count:0,
            priceBefore: '6,499',
            discount: '77% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'HD Display',
            usp3:'ENx Technology',
            image: smartwatch4,
        },
        {
            productid: 'smartwatches5',
            itemName: 'Wave Call',
            category: 'smart watches',
            rating: '4.9',
            sold: '49',
            price: 1699,
            count:0,
            priceBefore: '7,990',
            discount: '79% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'HD Curved Display',
            usp3:'Save Upto 10 Contacts',
            image: smartwatch5,
        },
        {
            productid: 'smartwatches6',
            itemName: 'Wave Electra',
            category: 'smart watches',
            rating: '4.8',
            sold: '28',
            price: 1799,
            count:0,
            priceBefore: '7,990',
            discount: '77% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'HD Display',
            usp3:'Built-in Games',
            image: smartwatch6,
        },
        {
            productid: 'smartwatches7',
            itemName: 'Wave Arcade',
            category: 'smart watches',
            rating: '4.9',
            sold: '52',
            price: 2199,
            count:0,
            priceBefore: '7,990',
            discount: '72% off',
            offer: 'none',
            usp: '1.8" HD Display',
            usp2 :'HD Display',
            usp3:'Built-in Games',
            image: smartwatch7,
        },
        {
            productid: 'smartwatches8',
            itemName: 'Wave Leap Call',
            category: 'smart watches',
            rating: '4.8',
            sold: '17',
            price: 1799,
            count:0,
            priceBefore: '6,990',
            discount: '74% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'100+ Watch Faces',
            usp3:'100+ Sports Mode',
            image: smartwatch8,
        },
        {
            productid: 'smartwatches9',
            itemName: 'Wave Fury',
            category: 'smart watches',
            rating: '4.9',
            sold: '17',
            price: 1299,
            count:0,
            priceBefore: '6,999',
            discount: '81% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'30 Days Battery Life',
            usp3:'1.83" HD Display',
            image: smartwatch9,
        },
        {
            productid: 'smartwatches10',
            itemName: 'Wave Astra',
            category: 'smart watches',
            rating: '4.4',
            sold: '26',
            price: 1999,
            count:0,
            priceBefore: '6,999',
            discount: '71% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'1.83" HD Display',
            usp3:'700+ Active Modes',
            image: smartwatch10,
        },
        {
            productid: 'smartwatches11',
            itemName: 'Wave Stride Wave',
            category: 'smart watches',
            rating: '4.4',
            sold: '16',
            price: 1899,
            count:0,
            priceBefore: '7,990',
            discount: '76% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'100+ Watch Faces',
            usp3:'100+ Sports Mode',
            image: smartwatch11,
        },
        {
            productid: 'smartwatches12',
            itemName: 'Primia Celestial',
            category: 'smart watches',
            rating: '4.6',
            sold: '17',
            price: 1999,
            count:0,
            priceBefore: '7,999',
            discount: '75% off',
            offer: 'none',
            usp: 'BT Calling',
            usp2 :'Functional Crown',
            usp3:'100+ Sports Mode',
            image: smartwatch12,
        },
    
]
export default smartWatchesList