import neckbands1 from './neckbands1.jpg'
import neckbands2 from './neckbands2.jpg'
import neckbands3 from './neckbands3.jpg'
import neckbands4 from './neckbands4.jpg'
import neckbands5 from './neckbands5.jpg'
import neckbands6 from './neckbands6.jpg'
import neckbands7 from './neckbands7.jpg'
import neckbands8 from './neckbands8.jpg'
import neckbands9 from './neckbands9.jpg'
import neckbands10 from './neckbands10.jpg'
import neckbands11 from './neckbands11.jpg'
import neckbands12 from './neckbands12.jpg'
const neckBandsList = [
    {
        productid: 'neckBands1',
        itemName: 'Rockerz 235 V2 ',
        category: 'neck bands',
        rating: '4.8',
        sold: '1074',
        price: '999',
        priceBefore: '2,990',
        discount: '67% off',
        offer: 'none',
        usp: '8 Hours Playback',
        usp2 :'10mm Drivers',
        usp3:'Fast Charging',
        image: neckbands1,
    },
    {
        productid: 'neckBands2',
        itemName: 'Rockerz 255 Pro+ ',
        category: 'neck bands',
        rating: '4.8',
        sold: '427',
        price: '1,299',
        priceBefore: '3,990',
        discount: '67% off',
        offer: 'none',
        usp: '40 Hours Playback',
        usp2 :'10mm Drivers',
        usp3:'boAt Signature Sound',
        image: neckbands2,
    },
    {
        productid: 'neckBands3',
        itemName: 'Rockerz 245 V2 ',
        category: 'neck bands',
        rating: '4.8',
        sold: '207',
        price: '1,099',
        priceBefore: '2,990',
        discount: '63% off',
        offer: 'none',
        usp: '8 Hours Playback',
        usp2 :'ASAP Charging',
        usp3:'Bluetooth v5.O',
        image: neckbands3,
    },
    {
        productid: 'neckBands4',
        itemName: 'Rockerz 103 Pro ',
        category: 'neck bands',
        rating: '4.9',
        sold: '27',
        price: '1,499',
        priceBefore: '7,990',
        discount: '81% off',
        offer: 'none',
        usp: '40 Hours Playback',
        usp2 :'ASAP Charging',
        usp3:'Bluetooth v5.O',
        image: neckbands4,
    },
    {
        productid: 'neckBands5',
        itemName: 'Rockerz 235 Pro ',
        category: 'neck bands',
        rating: '4.8',
        sold: '54',
        price: '849',
        priceBefore: '1,990',
        discount: '57% off',
        offer: 'none',
        usp: '20 Hours Playback',
        usp2 :'Voice Assistant',
        usp3:'ENx Technology',
        image: neckbands5,
    },
    {
        productid: 'neckBands6',
        itemName: 'Rockerz 333 Pro ',
        category: 'neck bands',
        rating: '4.9',
        sold: '166',
        price: '1,799',
        priceBefore: '2,990',
        discount: '40% off',
        offer: 'none',
        usp: '60 Hours Playback',
        usp2 :'ASAP Charge',
        usp3:'IPXS Water Resistance',
        image: neckbands6,
    },
    {
        productid: 'neckBands7',
        itemName: 'Rockerz 260 ',
        category: 'neck bands',
        rating: '4.9',
        sold: '109',
        price: '1,299',
        priceBefore: '2,499',
        discount: '48% off',
        offer: 'none',
        usp: '8 Hours Playback',
        usp2 :'10mm Drivers',
        usp3:'Fast Charging',
        image: neckbands7,
    },
    {
        productid: 'neckBands8',
        itemName: 'Rockerz 255 Neo',
        category: 'neck bands',
        rating: '4.8',
        sold: '27',
        price: '1,299',
        priceBefore: '2,499',
        discount: '57% off',
        offer: 'none',
        usp: '25 Hours Playback',
        usp2 :'BEAST Mode',
        usp3:'ENx Technology',
        image: neckbands8,
    },
    {
        productid: 'neckBands9',
        itemName: 'Rockerz 333 ANC ',
        category: 'neck bands',
        rating: '5.0',
        sold: '51',
        price: '1,899',
        priceBefore: '5,999',
        discount: '68% off',
        offer: 'none',
        usp: 'Noise Cancellation',
        usp2 :'25 Hours Playback',
        usp3:'ASAP Charge',
        image: neckbands9,
    },
    {
        productid: 'neckBands10',
        itemName: 'Rockerz 245 Pro ',
        category: 'neck bands',
        rating: '4.8',
        sold: '18',
        price: '1,199',
        priceBefore: '2,499',
        discount: '52% off',
        offer: 'none',
        usp: '35 Hours Playback',
        usp2 :'ASAP Charge',
        usp3:'ENx Technology',
        image: neckbands10,
    },
    {
        productid: 'neckBands11',
        itemName: 'Rockerz 330 Pro ',
        category: 'neck bands',
        rating: '4.9',
        sold: '54',
        price: '1,799',
        priceBefore: '2,990',
        discount: '40% off',
        offer: 'none',
        usp: '60 Hours Playback',
        usp2 :'10mm Drivers',
        usp3:'ENx Technology',
        image: neckbands11,
    },
    {
        productid: 'neckBands12',
        itemName: 'Rockerz 255F ',
        category: 'neck bands',
        rating: '4.8',
        sold: '46',
        price: '1,194',
        priceBefore: '2,990',
        discount: '60% off',
        offer: 'none',
        usp: '8 Hours Playback',
        usp2 :'IPX5 Water Resistance',
        usp3:'110 mAh Battery',
        image: neckbands12,
    },
]

export default neckBandsList